##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Copyright © dev-cetera.com & contributors.
##
## The use of this source code is governed by an MIT-style license described in
## the LICENSE file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_pwa_utils
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_pwa_utils
funding:
- https://www.patreon.com/c/t0mb3rr
- https://github.com/sponsors/t0mb3rr
- https://www.buymeacoffee.com/dev_cetera
description: Web utilities for progressive web applications (PWA). No-ops on non-web platforms.
version: 0.3.5
topics:
  - path-strategy
  - web
  - pwa
  - url
  - utility

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^6.0.0

